### PR TITLE
Apply polyfill to Ember.Engine in addition to Ember.Application

### LINKED ISSUE #47: Does not work with (lazy-loaded) engines
Only tested this with a lazy-loaded engine, but I would assume that eagerly bundled engines are also affected.

Since the runtime polyfill only patches the [`buildRegistry` method](https://github.com/emberjs/ember.js/blob/v3.4.1/packages/%40ember/application/lib/application.js#L1062) of the [`Application` class](https://www.emberjs.com/api/ember/3.4/classes/Application), it has no effect on engines:

https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/blob/53afc725e13d8db63bf8006c0c906969441482de/vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js#L57-L60

Which is why it causes this error:

```
Uncaught Error: Assertion Failed: You cannot use 'SomeComponent' as a component name. Component names must contain a hyphen
```

I understand that `Application` extends [`Engine`](https://www.emberjs.com/api/ember/3.4/classes/Engine), but that this polyfill has to patch `Application` instead of `Engine`, because it needs to override some registry entries only defined in `Application`:

https://github.com/emberjs/ember.js/blob/v3.4.1/packages/%40ember/application/lib/application.js#L1091-L1093

I now tried running the same polyfill for `Engine` _in addition_ to `Application` and so far it seems to work. 🤷‍♂️ 

This is not ideal for `Application` though, because the polyfill is:

- registered in `Engine`
- then overridden in `Application`
- and then registered again in `Application`

Do you still think that this is a valid solution going forward? I will submit a PR then.

### PR DESCRIPTION
**Pull request by pgengler**
This is an updated version of the changes in #48, to fix #47. Like that PR, it applies the polyfill to both Ember.Application and Ember.Engine; since Ember.Application extends from Ember.Engine this might be unnecessary and the polyfill need only be applied to Ember.Engine, but this way is unlikely to break anything. (Happy to update the PR if it's preferable to just apply to Ember.Engine.)

There aren't a lot of non-whitespace changes here; you might want to use Github's "Hide whitespace changes" feature to see the substantive changes.

### CODE REVIEW

**Comment by pgengler** [comment]
I added another commit that fixes the "prettier" errors that came up in CI. Oddly, I didn't get them locally (in my local setup, prettier tells me to do the opposite of what the CI run wanted me to do). This passes in CI at least...

**Comment by rwjblue** [comment]
Thank you @pgengler

File: vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js [hunk 1]
```diff
@@ -245,176 +407,16 @@ import { lte, gte } from 'ember-compatibility-helpers';
...
-          };
-          Environment.create.__IS_ANGLE_BRACKET_PATCHED__ = true;
-        }
-
-        return registry;
-      },
-    });
+      return registry;
+    };
+    for (const PolyfillTarget of [Application, Engine]) {
```
Comment (rwjblue) [inline vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js:417]: Sadly, I don't think we can use `for of` loops (because it ends up requiring `Symbol` which is not available on IE11), would you mind rewriting as either a plain `for` or `.forEach`?

Comment (pgengler) [reply vendor/angle-bracket-invocation-polyfill/runtime-polyfill.js]: Done... rather than replace it with a different loop I just unrolled it, since it was only two elements.
